name: bigus_4
description: "A new Flutter project."
publish_to: 'none' 


environment:
  sdk: ^3.5.3

dependencies:
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  flutter_gen: ^5.8.0
  intl_utils: ^2.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.20.1
  flutter_lints: ^5.0.0

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter:
  uses-material-design: true